### ISSUE TITLE
Progress tracker/phases/ideas

### ISSUE THREAD

**Issue by Cybermaxke** [LanternPowered/Porygen#2]
The follow is a vague structure of how the project will be built, feel free to post your own ideas that you would like to see.

**Generator:**

- [ ] 1. **Infinite polygonal cell generator and processing**
  - [x] 1. Cell generation, borders, center, etc.
  - [x] 2. Generate images
  - [x] 3. Generate land/ocean, distance to land/ocean
  - [x] 4. Generate rivers
  - [x] 5. Generate moisture map
  - [ ] 6. Generate temperature map
  - [ ] 7. Generate biomes from moisture, temperature, or other factors
- [ ] 2. **Minecraft biome generator** (minecraft world, per chunk, per block)
  - [ ] 1. Testing with vanilla Minecraft (using Sponge) along the way
  - [ ] 2. Simple generation (base biomes)
  - [ ] 3. Generate river biomes on borders
  - [ ] 4. Generate edge biomes
  - [ ] 5. More advanced stuff?
- [ ] 3. **Minecraft world generator**
  - [ ] 1. Simple terrain generation
  - [ ] 2. More advanced terrain generation?
  - [ ] 3. Tree generation and population
  - [ ] 4. More terrain population
  - [ ] 5. Basic structures
  - [ ] 6. Caves
  - [ ] 7. Etc.
- [ ] 4. **Entity population** (requires unavailable API)
  - [ ] 1. Population of entities accross the biomes, based on location of cells?
  - [ ] 2. Staying longer in a cell increases the difficulty of entities (syncing difficulty of all chunks within the cell to be compatible with vanilla)
5. **Extras?**
    1. Generating a roadmap
    2. Generate towns along the road
    3. Generate stairs/bridges/ladders/etc. to cross cliffs or move down
    4. Traveling villagers along the road, "Traveling Merchant"?
    5. Underground structures: mineshafts, dungeons, etc.
    6. Etc.

**Node editor:**
Design a node editor which allows you to configure your own world, visually using the noise generators, cell generators, processors, etc.
